version: '3.9'

services:
  app:
    build: .
    ports:
      - "8007:8007"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_student7
      MYSQL_USER: student7
      MYSQL_PASSWORD: '@studentdummy'
      MYSQL_ROOT_PASSWORD: '@studentdummy'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
